import { useMemo,useState } from 'react'
import { Icon } from '../components/ui/Icon'
import { useGym } from '../context/GymContext'
import type { Member } from '../types/domain'
export function Topbar({title,onSelect,onLogout}:{title:string;onSelect:(m:Member)=>void;onLogout:()=>void}){
  const{data,online,syncing,syncNow,mode,desktop}=useGym()
  const[q,setQ]=useState('');const[open,setOpen]=useState(false);const[at,setAt]=useState(0)
  const results=useMemo(()=>{const v=q.trim().toLowerCase();return v?data.members.filter(m=>[m.name,m.id,m.phone,m.plan].some(f=>f.toLowerCase().includes(v))).slice(0,6):[]},[q,data.members])
  const choose=(m:Member)=>{onSelect(m);setQ('');setOpen(false)}
  const nativeSync=desktop?.snapshot?.memberSync
  const status=mode==='desktop'?(syncing?'MEMBERS SYNCING':online?'MEMBERS ONLINE':desktop?.authStatus?.offline?'OFFLINE':'LOCAL'):online?'ONLINE':'OFFLINE'
  const detail=desktop?`${desktop.snapshot?.pending??0} PENDING · ${nativeSync?.available?'MEMBER SYNC':desktop.authStatus?.authenticated?'SIGN IN TO SYNC':'NO SERVER'}`:syncing?'SYNCING':data.queue.length?`${data.queue.length} PENDING`:'SYNCED'
  return <header className="topbar"><div><span className="eyebrow">ARMSTRONG FITNESS</span><h1>{title}</h1></div><div className="top-actions"><div className="global-search"><label className="search"><Icon name="search" size={17}/><input value={q} onChange={e=>{setQ(e.target.value);setOpen(true);setAt(0)}} onFocus={()=>setOpen(true)} onKeyDown={e=>{if(!results.length)return;if(e.key==='ArrowDown'){e.preventDefault();setAt((at+1)%results.length)}if(e.key==='ArrowUp'){e.preventDefault();setAt((at-1+results.length)%results.length)}if(e.key==='Enter'){e.preventDefault();choose(results[at])}if(e.key==='Escape')setOpen(false)}} placeholder="Search members by name, ID or phone..."/></label>{open&&q.trim()&&<div className="search-results"><div className="search-result-head"><span>Members</span><small>{results.length} results</small></div>{results.map((m,i)=><button key={m.id} className={i===at?'selected':''} onMouseDown={e=>{e.preventDefault();choose(m)}}><span className="avatar tiny">{m.initials}</span><span className="result-main"><b>{m.name}</b><small>{m.id} · {m.phone}</small></span><span className="result-plan">{m.plan}</span></button>)}{!results.length&&<div className="empty-search"><b>No members found</b></div>}</div>}</div><button className="sync" disabled={syncing} onClick={()=>void syncNow()} title={desktop?'Member synchronization only. Other modules remain local.':undefined}><span className="status-dot" style={{background:online?'var(--green)':'var(--red)'}}/>{status}<span className="divider"/>{detail}</button><button className="profile" onClick={onLogout} disabled={mode==='desktop'&&!desktop?.authStatus?.authenticated} title={mode==='desktop'&&!desktop?.authStatus?.authenticated?'Sign in to use this computer':'Sign out'}><span className="avatar small">{mode==='desktop'?(desktop?.authStatus?.userName?.[0]??'L'):'P'}</span><span><b>{mode==='desktop'?(desktop?.authStatus?.userName??'Local operator'):'Prinzz'}</b><small>{mode==='desktop'?(desktop?.authStatus?.authenticated?'Administrator · Sign out':'Unauthenticated'):'Administrator · Sign out'}</small></span></button></div></header>
}
